QOL Police Changes
qbcore-framework/qb-policejob pull request #326
Opened 2022-06-12 18:33 UTC by Holidayy95

Added Progress bars to 2 commands

Added a 'Fine' Command

2022-06-13 14:04 UTC, FjamZoo requested changes

2022-06-13 14:04 UTC, FjamZoo commented on client/job.lua
> +                QBCore.Functions.Progressbar("police_status", "Impounding Vehicle..", 10000, false, true, {
Why is this saying impoundinv vehicle when it should be checking status? Might just be a typo from copy paste,

2022-06-13 14:04 UTC, FjamZoo commented on server/main.lua
> +        if OtherPlayer ~= nil then
You can chance 

`if OtherPlayer ~= nil then` to just `if OtherPlayer then`

2022-06-13 14:12 UTC, Holidayy95 commented
Also this goes with it, if you want the webhook

https://github.com/qbcore-framework/qb-smallresources/pull/234

2022-06-16 16:52 UTC, FjamZoo commented
Hey, I saw that your server sided command for fining people does not have a distance check which means anyone can bill any player no matter of distance if you could update that to make it more secure, we would happily merge this into the Police Job

2022-06-16 16:56 UTC, FjamZoo commented
Also instead of checking for multiple jobs server side please just use that way we dont need to add 100s of PoliceJobs

`PlayerData.job.type == "leo"`

2022-07-28 05:01 UTC, closed without merging